sudo: required
dist: trusty
services:
  - postgresql
addons:
  postgresql: '9.5'
language: node_js
node_js:
  - 4
  - 6
  - 8
  - 9
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm install sqlite3
script:
  - 'npm run test'
after_success:
  - 'npm run cover:up'
notifications:
  email: false
