sudo: required
dist: trusty
services:
  - postgresql
addons:
  postgresql: '9.5'
language: node_js
node_js:
  - 10
  - 12
  - 14
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm install sqlite3
script:
  - 'npm run test:ci'
after_success:
  - 'npm run codecov'
notifications:
  email: false
